/*
 * This file is generated by scripts/generate-props.js.
 * Do not edit manually.
 */

export type VueGridLayoutProp = {
  name: string
  component: 'VueGridLayout' | 'ResponsiveVueGridLayout' | 'WidthProvider'
  definedIn: string
  description: string | null
  vueRuntimeTypes: string[]
  tsType: string | null
  sourceType: string | null
  default: string | null
  hasDefault: boolean
  defaultIsFactory: boolean
  required: boolean | null
  validator: string | null
  source: { file: string }
}

export const VUE_GRID_LAYOUT_PROPS: VueGridLayoutProp[] = [
  {
    "name": "class",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Additional CSS class for the container",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "''",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<string>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "style",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Inline style object for the container",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "CSSProperties",
    "default": "() => ({})",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<CSSProperties>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "width",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Container width (px); auto-measured via WidthProvider if not provided",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "autoSize",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Automatically adjust container height based on content",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "cols",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Number of columns, default 12",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "12",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number as PropType<number>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "draggableCancel",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "CSS selector for elements that should not trigger drag (requires . prefix)",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "''",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<string>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "draggableHandle",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "CSS selector for drag handle elements (requires . prefix)",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "''",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<string>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "verticalCompact",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Vertical compact layout (deprecated, use compactType)",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "compactType",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Compaction direction: vertical / horizontal / null (no compaction)",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "CompactType",
    "default": "'vertical'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": "(value: CompactType) => value == null || ['vertical', 'horizontal'].includes(value)",
    "sourceType": "String as PropType<CompactType>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "modelValue",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Layout array, supports v-model two-way binding",
    "vueRuntimeTypes": [
      "Array"
    ],
    "tsType": "Layout",
    "default": "() => []",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": "(layout: unknown) => { if (!Array.isArray(layout)) return false; for (let i = 0; i < layout.length; i++) { const item = layout[i] as { x?: unknown; y?: unknown; w?: unknown; h?: unknown; i?: unknown; } | null; if (!item) return false; if (typeof item.x !== \"number\" || Number.isNaN(item.x)) return false; if (typeof item.y !== \"number\" || Number.isNaN(item.y)) return false; if (typeof item.w !== \"number\" || Number.isNaN(item.w)) return false; if (typeof item.h !== \"number\" || Number.isNaN(item.h)) return false; if (typeof item.i !== \"undefined\" && typeof item.i !== \"string\") { return false; } } return true; }",
    "sourceType": "Array as PropType<Layout>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "margin",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Grid spacing [x, y] in px, default [10, 10]",
    "vueRuntimeTypes": [
      "Array"
    ],
    "tsType": "Array<number>",
    "default": "() => [10, 10]",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": "(value: number[]) => { return value.every(item => typeof item === 'number'); }",
    "sourceType": "Array as PropType<Array<number>>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "containerPadding",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Container padding [x, y] in px, defaults to margin value",
    "vueRuntimeTypes": [
      "Array"
    ],
    "tsType": "number[]",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": "(value: number[]) => { return value.every(item => typeof item === 'number'); }",
    "sourceType": "Array as PropType<number[]>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "rowHeight",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Row height (px), default 150",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "150",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number as PropType<number>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "maxRows",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Maximum number of rows, default Infinity (no limit)",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "Infinity",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number as PropType<number>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "isBounded",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Restrict dragging within container boundaries",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "isDraggable",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Globally enable dragging, default true",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "isResizable",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Globally enable resizing, default true",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "allowOverlap",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Allow grid items to overlap, automatically enables preventCollision",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "preventCollision",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Prevent collision mode, items won't push others when dragging",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "useCSSTransforms",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Use CSS transform for positioning (better performance), default true",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "transformScale",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Set scale ratio when parent has CSS scale transform",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": "1",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Number as PropType<number>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "autoScroll",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Auto-scroll when dragging near edges; accepts boolean or { margin, speed } object",
    "vueRuntimeTypes": [
      "Boolean",
      "Object"
    ],
    "tsType": "boolean | { margin?: number; speed?: number }",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "[Boolean, Object] as PropType<boolean | { margin?: number; speed?: number }>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "isDroppable",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Allow dropping elements from outside, requires @drop and @dropDragOver handlers",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "dropStrategy",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Drop positioning strategy: cursor (mouse position) / auto (auto-snap)",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "'cursor' | 'auto'",
    "default": "'cursor'",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": "(value: string) => ['cursor', 'auto'].includes(value)",
    "sourceType": "String as PropType<'cursor' | 'auto'>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "resizeHandles",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Array of enabled resize handle directions, e.g. [\"se\", \"n\", \"e\"]",
    "vueRuntimeTypes": [
      "Array"
    ],
    "tsType": "Array<'s' | 'w' | 'e' | 'n' | 'sw' | 'nw' | 'se' | 'ne'>",
    "default": "() => ['se']",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Array as PropType<Array<'s' | 'w' | 'e' | 'n' | 'sw' | 'nw' | 'se' | 'ne'>>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "resizeHandle",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Custom resize handle render function or VNode",
    "vueRuntimeTypes": [
      "Object",
      "Function"
    ],
    "tsType": "ResizeHandle",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "[Object, Function] as PropType<ResizeHandle>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "historyStore",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Pinia history store instance for undo/redo functionality",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "GridHistoryStore",
    "default": "null",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<GridHistoryStore>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "droppingItem",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Placeholder config for external drop { i, w, h }",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "DroppingItem",
    "default": "() => ({ i: \"__dropping-elem__\", h: 1, w: 1 })",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": "(value: DroppingItem) => { return ( typeof value.i === 'string' && typeof value.w === 'number' && typeof value.h === 'number' ); }",
    "sourceType": "Object as PropType<DroppingItem>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  },
  {
    "name": "innerRef",
    "component": "VueGridLayout",
    "definedIn": "basicProps",
    "description": "Ref reference to container DOM element",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "Ref<HTMLElement>",
    "default": "() => null",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<Ref<HTMLElement>>",
    "source": {
      "file": "lib/VueGridLayoutPropTypes.ts"
    }
  }
]

export const RESPONSIVE_VUE_GRID_LAYOUT_PROPS: VueGridLayoutProp[] = [
  {
    "name": "breakpoint",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Force current breakpoint key (optional, usually auto-calculated)",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "''",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "breakpoints",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Breakpoint to pixel width mapping, e.g. { lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "unknown",
    "default": "() => ({ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 })",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as () => BreakpointMap",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "allowOverlap",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Allow grid items to overlap",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "verticalCompact",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Vertical compact layout (deprecated)",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "true",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "cols",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Breakpoint to column count mapping, e.g. { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "unknown",
    "default": "() => ({ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 })",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as () => BreakpointMap",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "margin",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Breakpoint to spacing mapping or universal [x, y], e.g. { lg: [10, 10] } or [10, 10]",
    "vueRuntimeTypes": [
      "Array",
      "Object"
    ],
    "tsType": "MarginPaddingMap | [number, number]",
    "default": "() => ([10, 10])",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "[Array, Object] as PropType<MarginPaddingMap | [number, number]>",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "containerPadding",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Breakpoint to container padding mapping or universal value",
    "vueRuntimeTypes": [
      "Array",
      "Object"
    ],
    "tsType": "MarginPaddingMap | [number, number]",
    "default": "() => ({ lg: null, md: null, sm: null, xs: null, xxs: null })",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "[Array, Object] as PropType<MarginPaddingMap | [number, number]>",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "layouts",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Layout collection for each breakpoint, e.g. { lg: Layout[], md: Layout[] }",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "LayoutsMap",
    "default": "() => ({})",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<LayoutsMap>",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "width",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Component width (required, usually auto-provided by WidthProvider)",
    "vueRuntimeTypes": [
      "Number"
    ],
    "tsType": "number",
    "default": null,
    "hasDefault": false,
    "defaultIsFactory": false,
    "required": true,
    "validator": null,
    "sourceType": "Number",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  },
  {
    "name": "compactType",
    "component": "ResponsiveVueGridLayout",
    "definedIn": "defineComponent.props",
    "description": "Compaction direction: vertical / horizontal / null",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "CompactType",
    "default": "\"vertical\"",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": "(value: CompactType) => value == null || ['vertical', 'horizontal'].includes(value)",
    "sourceType": "String as PropType<CompactType>",
    "source": {
      "file": "lib/ResponsiveVueGridLayout.tsx"
    }
  }
]

export const WIDTH_PROVIDER_PROPS: VueGridLayoutProp[] = [
  {
    "name": "measureBeforeMount",
    "component": "WidthProvider",
    "definedIn": "defineComponent.props",
    "description": "Measure width before first render to avoid layout shift (recommended for SSR)",
    "vueRuntimeTypes": [
      "Boolean"
    ],
    "tsType": "boolean",
    "default": "false",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "Boolean as PropType<boolean>",
    "source": {
      "file": "lib/WidthProvider.tsx"
    }
  },
  {
    "name": "class",
    "component": "WidthProvider",
    "definedIn": "defineComponent.props",
    "description": "Additional CSS class for the container",
    "vueRuntimeTypes": [
      "String"
    ],
    "tsType": "string",
    "default": "''",
    "hasDefault": true,
    "defaultIsFactory": false,
    "required": null,
    "validator": null,
    "sourceType": "String as PropType<string>",
    "source": {
      "file": "lib/WidthProvider.tsx"
    }
  },
  {
    "name": "style",
    "component": "WidthProvider",
    "definedIn": "defineComponent.props",
    "description": "Container style object",
    "vueRuntimeTypes": [
      "Object"
    ],
    "tsType": "Kv",
    "default": "() => ({})",
    "hasDefault": true,
    "defaultIsFactory": true,
    "required": null,
    "validator": null,
    "sourceType": "Object as PropType<Kv>",
    "source": {
      "file": "lib/WidthProvider.tsx"
    }
  }
]
